#!/usr/bin/env python3
import json

# all_elements = [{'element': 1, 'sysmbol': 'H', 'name': 'Hydrogen'},
#                 {'element': 2, 'sysmbol': 'He', 'name': 'Helium'},
#                 {'element': 3, 'sysmbol': 'Li', 'name': 'Lithium'},
#                 {'element': 4, 'sysmbol': 'Be', 'name': 'Beryllium'},
#                 {'element': 5, 'sysmbol': 'B', 'name': 'Boron'},
#                 {'element': 6, 'sysmbol': 'C', 'name': 'Carbon'},
#                 {'element': 7, 'sysmbol': 'N', 'name': 'Nitrogen'},
#                 {'element': 8, 'sysmbol': 'O', 'name': 'Oxygen'},
#                 {'element': 9, 'sysmbol': 'F', 'name': 'Fluorine'},
#                 {'element': 10, 'sysmbol': 'Ne', 'name': 'Neon'},
#                 {'element': 11, 'sysmbol': 'Na', 'name': 'Sodium'},
#                 {'element': 12, 'sysmbol': 'Mg', 'name': 'Magnesium'},
#                 {'element': 13, 'sysmbol': 'Al', 'name': 'Aluminum'},
#                 {'element': 14, 'sysmbol': 'Si', 'name': 'Silicon'},
#                 {'element': 15, 'sysmbol': 'P', 'name': 'Phosphorus'},
#                 {'element': 16, 'sysmbol': 'S', 'name': 'Sulfur'},
#                 {'element': 17, 'sysmbol': 'Cl', 'name': 'Chlorine'},
#                 {'element': 18, 'sysmbol': 'Ar', 'name': 'Argon'},
#                 {'element': 19, 'sysmbol': 'K', 'name': 'Potassium'},
#                 {'element': 20, 'sysmbol': 'Ca', 'name': 'Calcium'},
#                 {'element': 21, 'sysmbol': 'Sc', 'name': 'Scandium'},
#                 {'element': 22, 'sysmbol': 'Ti', 'name': 'Titanium'},
#                 {'element': 23, 'sysmbol': 'V', 'name': 'Vanadium'},
#                 {'element': 24, 'sysmbol': 'Cr', 'name': 'Chromium'},
#                 {'element': 25, 'sysmbol': 'Mn', 'name': 'Manganese'},
#                 {'element': 26, 'sysmbol': 'Fe', 'name': 'Iron'},
#                 {'element': 27, 'sysmbol': 'Co', 'name': 'Cobalt'},
#                 {'element': 28, 'sysmbol': 'Ni', 'name': 'Nickel'},
#                 {'element': 29, 'sysmbol': 'Cu', 'name': 'Copper'},
#                 {'element': 30, 'sysmbol': 'Zn', 'name': 'Zinc'},
#                 {'element': 31, 'sysmbol': 'Ga', 'name': 'Gallium'},
#                 {'element': 32, 'sysmbol': 'Ge', 'name': 'Germanium'},
#                 {'element': 33, 'sysmbol': 'As', 'name': 'Arsenic'},
#                 {'element': 34, 'sysmbol': 'Se', 'name': 'Selenium'},
#                 {'element': 35, 'sysmbol': 'Br', 'name': 'Bromine'},
#                 {'element': 36, 'sysmbol': 'Kr', 'name': 'Krypton'},
#                 {'element': 37, 'sysmbol': 'Rb', 'name': 'Rubidium'},
#                 {'element': 38, 'sysmbol': 'Sr', 'name': 'Strontium'},
#                 {'element': 39, 'sysmbol': 'Y', 'name': 'Yttrium'},
#                 {'element': 40, 'sysmbol': 'Zr', 'name': 'Zirconium'},
#                 {'element': 41, 'sysmbol': 'Nb', 'name': 'Niobium'},
#                 {'element': 42, 'sysmbol': 'Mo', 'name': 'Molybdenum'},
#                 {'element': 43, 'sysmbol': 'Tc', 'name': 'Technetium'},
#                 {'element': 44, 'sysmbol': 'Ru', 'name': 'Ruthenium'},
#                 {'element': 45, 'sysmbol': 'Rh', 'name': 'Rhodium'},
#                 {'element': 46, 'sysmbol': 'Pd', 'name': 'Palladium'},
#                 {'element': 47, 'sysmbol': 'Ag', 'name': 'Silver'},
#                 {'element': 48, 'sysmbol': 'Cd', 'name': 'Cadmium'},
#                 {'element': 49, 'sysmbol': 'In', 'name': 'Indium'},
#                 {'element': 50, 'sysmbol': 'Sn', 'name': 'Tin'},
#                 {'element': 51, 'sysmbol': 'Sb', 'name': 'Antimony'},
#                 {'element': 52, 'sysmbol': 'Te', 'name': 'Tellurium'},
#                 {'element': 53, 'sysmbol': 'I', 'name': 'Iodine'},
#                 {'element': 54, 'sysmbol': 'Xe', 'name': 'Xenon'},
#                 {'element': 55, 'sysmbol': 'Cs', 'name': 'Cesium'},
#                 {'element': 56, 'sysmbol': 'Ba', 'name': 'Barium'},
#                 {'element': 57, 'sysmbol': 'La', 'name': 'Lanthanum'},
#                 {'element': 58, 'sysmbol': 'Ce', 'name': 'Cerium'},
#                 {'element': 59, 'sysmbol': 'Pr', 'name': 'Praseodymium'},
#                 {'element': 60, 'sysmbol': 'Nd', 'name': 'Neodymium'},
#                 {'element': 61, 'sysmbol': 'Pm', 'name': 'Promethium'},
#                 {'element': 62, 'sysmbol': 'Sm', 'name': 'Samarium'},
#                 {'element': 63, 'sysmbol': 'Eu', 'name': 'Europium'},
#                 {'element': 64, 'sysmbol': 'Gd', 'name': 'Gadolinium'},
#                 {'element': 65, 'sysmbol': 'Tb', 'name': 'Terbium'},
#                 {'element': 66, 'sysmbol': 'Dy', 'name': 'Dysprosium'},
#                 {'element': 67, 'sysmbol': 'Ho', 'name': 'Holmium'},
#                 {'element': 68, 'sysmbol': 'Er', 'name': 'Erbium'},
#                 {'element': 69, 'sysmbol': 'Tm', 'name': 'Thulium'},
#                 {'element': 70, 'sysmbol': 'Yb', 'name': 'Ytterbium'},
#                 {'element': 71, 'sysmbol': 'Lu', 'name': 'Lutetium'},
#                 {'element': 72, 'sysmbol': 'Hf', 'name': 'Hafnium'},
#                 {'element': 73, 'sysmbol': 'Ta', 'name': 'Tantalum'},
#                 {'element': 74, 'sysmbol': 'W', 'name': 'Tungsten'},
#                 {'element': 75, 'sysmbol': 'Re', 'name': 'Rhenium'},
#                 {'element': 76, 'sysmbol': 'Os', 'name': 'Osmium'},
#                 {'element': 77, 'sysmbol': 'Ir', 'name': 'Iridium'},
#                 {'element': 78, 'sysmbol': 'Pt', 'name': 'Platinum'},
#                 {'element': 79, 'sysmbol': 'Au', 'name': 'Gold'},
#                 {'element': 80, 'sysmbol': 'Hg', 'name': 'Mercury'},
#                 {'element': 81, 'sysmbol': 'Tl', 'name': 'Thallium'},
#                 {'element': 82, 'sysmbol': 'Pb', 'name': 'Lead'},
#                 {'element': 83, 'sysmbol': 'Bi', 'name': 'Bismuth'},
#                 {'element': 84, 'sysmbol': 'Po', 'name': 'Polonium'},
#                 {'element': 85, 'sysmbol': 'At', 'name': 'Astatine'},
#                 {'element': 86, 'sysmbol': 'Rn', 'name': 'Radon'},
#                 {'element': 87, 'sysmbol': 'Fr', 'name': 'Francium'},
#                 {'element': 88, 'sysmbol': 'Ra', 'name': 'Radium'},
#                 {'element': 89, 'sysmbol': 'Ac', 'name': 'Actinium'},
#                 {'element': 90, 'sysmbol': 'Th', 'name': 'Thorium'},
#                 {'element': 91, 'sysmbol': 'Pa', 'name': 'Protactinium'},
#                 {'element': 92, 'sysmbol': 'U', 'name': 'Uranium'},
#                 {'element': 93, 'sysmbol': 'Np', 'name': 'Neptunium'},
#                 {'element': 94, 'sysmbol': 'Pu', 'name': 'Plutonium'},
#                 {'element': 95, 'sysmbol': 'Am', 'name': 'Americium'},
#                 {'element': 96, 'sysmbol': 'Cm', 'name': 'Curium'},
#                 {'element': 97, 'sysmbol': 'Bk', 'name': 'Berkelium'},
#                 {'element': 98, 'sysmbol': 'Cf', 'name': 'Californium'},
#                 {'element': 99, 'sysmbol': 'Es', 'name': 'Einsteinium'},
#                 {'element': 100, 'sysmbol': 'Fm', 'name': 'Fermium'},
#                 {'element': 101, 'sysmbol': 'Md', 'name': 'Mendelevium'},
#                 {'element': 102, 'sysmbol': 'No', 'name': 'Nobelium'},
#                 {'element': 103, 'sysmbol': 'Lr', 'name': 'Lawrencium'},
#                 {'element': 104, 'sysmbol': 'Rf', 'name': 'Rutherfordium'},
#                 {'element': 105, 'sysmbol': 'Db', 'name': 'Dubnium'},
#                 {'element': 106, 'sysmbol': 'Sg', 'name': 'Seaborgium'},
#                 {'element': 107, 'sysmbol': 'Bh', 'name': 'Bohrium'},
#                 {'element': 108, 'sysmbol': 'Hs', 'name': 'Hassium'},
#                 {'element': 109, 'sysmbol': 'Mt', 'name': 'Meitnerium'},
#                 {'element': 110, 'sysmbol': 'Ds', 'name': 'Darmstadtium'},
#                 {'element': 111, 'sysmbol': 'Rg', 'name': 'Roentgenium'},
#                 {'element': 112, 'sysmbol': 'Cn', 'name': 'Copernicium'},
#                 {'element': 113, 'sysmbol': 'Nh', 'name': 'Nihonium'},
#                 {'element': 114, 'sysmbol': 'Fl', 'name': 'Flerovium'},
#                 {'element': 115, 'sysmbol': 'Mc', 'name': 'Moscovium'},
#                 {'element': 116, 'sysmbol': 'Lv', 'name': 'Livermorium'},
#                 {'element': 117, 'sysmbol': 'Ts', 'name': 'Tennessine'},
#                 {'element': 118, 'sysmbol': 'Og', 'name': 'Oganesson'},
#                 {'element': 0, 'sysmbol': 'X', 'name': 'Unknown'}]

all_elements = json.load(open('elements.txt'))

ans = []
for element in all_elements:
    if element['name'][-3:] == "ium":
        ans.append(element)

# ans = [element for element in all_elements if element['name'][-3:] == "ium"]

print(ans)
